Repository Oden-EAG/hp3d, pull requests merged in 2023-02, with the labels that each got.

#62 Minor changes to problem makefiles and OMP fix
  trunk/makefile
  trunk/problems/LASER/COMMON_FILES/set_environment.F90
  trunk/problems/LASER/UW_COUPLED/main.F90
  trunk/problems/LASER/UW_COUPLED/makefile
  trunk/problems/MAXWELL/GALERKIN/common/set_environment.F90
  trunk/problems/MAXWELL/GALERKIN/main.F90
  trunk/problems/MAXWELL/GALERKIN/makefile
  trunk/problems/MPI_TEST/TEST/common/set_environment.F90
  trunk/problems/MPI_TEST/TEST/makefile
  trunk/problems/POISSON/GALERKIN/common/set_environment.F90
  trunk/problems/POISSON/GALERKIN/main.F90
  trunk/problems/POISSON/GALERKIN/makefile
  trunk/problems/POISSON/PRIMAL_DPG/common/set_environment.F90
  trunk/problems/POISSON/PRIMAL_DPG/main.F90
  trunk/problems/POISSON/PRIMAL_DPG/makefile
  trunk/problems/SHEATHED_HOSE/makefile
  trunk/problems/VECTOR_POISSON/GALERKIN/common/set_environment.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/main.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/makefile
Labels: minor, ready-for-review, application

#61 changes to flag_constr_parents.F and close_mesh.F90
  trunk/src/constrs/flag_constr_parents.F
  trunk/src/meshmod/close_mesh.F90
Labels: bug, ready-for-review

#64 Minor fix omp 2
  trunk/problems/MPI_TEST/TEST/main.F90
Labels: minor, application
