Repository Oden-EAG/hp3d, pull requests merged in 2023-03, with the labels that each got.

#66 Minor make fix
  README.md
  trunk/m_options_files/m_options_LC
  trunk/m_options_files/m_options_TACC_intel18
  trunk/m_options_files/m_options_TACC_intel19
  trunk/m_options_files/m_options_cent_os_7
  trunk/m_options_files/m_options_debian_10
  trunk/m_options_files/m_options_mac_os_13
  trunk/makefile
  trunk/problems/LASER/UW_COUPLED/make.inc
  trunk/problems/LASER/UW_COUPLED/makefile
  trunk/problems/MAXWELL/GALERKIN/exec_case.F90
  trunk/problems/MAXWELL/GALERKIN/make.inc
  trunk/problems/MAXWELL/GALERKIN/makefile
  trunk/problems/MPI_TEST/TEST/make.inc
  trunk/problems/MPI_TEST/TEST/makefile
  trunk/problems/POISSON/GALERKIN/exec_case.F90
  trunk/problems/POISSON/GALERKIN/make.inc
  trunk/problems/POISSON/GALERKIN/makefile
  trunk/problems/POISSON/PRIMAL_DPG/exec_case.F90
  trunk/problems/POISSON/PRIMAL_DPG/make.inc
  trunk/problems/POISSON/PRIMAL_DPG/makefile
  trunk/problems/SHEATHED_HOSE/exec_case.F90
  trunk/problems/SHEATHED_HOSE/make.inc
  trunk/problems/SHEATHED_HOSE/makefile
  trunk/problems/VECTOR_POISSON/GALERKIN/exec_case.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/make.inc
  trunk/problems/VECTOR_POISSON/GALERKIN/makefile
  trunk/src/modules/mkl_spblas.F90
  trunk/src/solver/frontal/base/complex/makefile
  trunk/src/solver/frontal/base/real/makefile
Labels: minor, ready-for-review, make

#70 Distributing the initial mesh by default
  trunk/problems/LASER/UW_COUPLED/initialize.F90
  trunk/problems/MAXWELL/GALERKIN/common/initialize.F90
  trunk/problems/MPI_TEST/TEST/common/initialize.F90
  trunk/problems/POISSON/GALERKIN/common/initialize.F90
  trunk/problems/POISSON/GALERKIN/main.F90
  trunk/problems/POISSON/GALERKIN/run.sh
  trunk/problems/POISSON/PRIMAL_DPG/common/initialize.F90
  trunk/problems/SHEATHED_HOSE/common/initialize.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/common/initialize.F90
  trunk/src/GMP/base/input_DEFAULT.F90
  trunk/src/meshgen/hp3gen.F90
Labels: enhancement, ready-for-review

#72 Optimizations for elem_nodes
  trunk/src/meshmod/util/elem_nodes.F90
  trunk/src/meshmod/util/elem_nodes_one.F90
  trunk/src/modules/element_data.F
  trunk/src/modules/node_types.F90
Labels: enhancement, minor, ready-for-review

#83 Makefile modifications
  trunk/m_options_files/m_options_LC
  trunk/m_options_files/m_options_TACC_intel18
  trunk/m_options_files/m_options_TACC_intel19
  trunk/m_options_files/m_options_cent_os_7
  trunk/m_options_files/m_options_debian_10
  trunk/m_options_files/m_options_mac_os_13
  trunk/makefile
  trunk/problems/LASER/UW_COUPLED/makefile
  trunk/problems/MAXWELL/GALERKIN/makefile
  trunk/problems/MPI_TEST/TEST/makefile
  trunk/problems/POISSON/GALERKIN/makefile
  trunk/problems/POISSON/PRIMAL_DPG/makefile
  trunk/problems/PRIMAL_DPG_HEEDONG/makefile
  trunk/problems/SHEATHED_HOSE/makefile
  trunk/problems/VECTOR_POISSON/GALERKIN/makefile
Labels: minor, ready-for-review, make

#78 Removing `type node%geom_interf` flag
  trunk/src/datstrs/result.F90
  trunk/src/hpinterp/update_Ddof.F90
  trunk/src/hpinterp/update_gdof.F90
  trunk/src/meshmod/nodgen.F90
  trunk/src/modules/data_structure3D.F90
Labels: bug, enhancement, ready-for-review

#80 Subd bug fix
  trunk/src/adapt/global_href.F90
  trunk/src/meshmod/close_mesh.F90
  trunk/src/meshmod/refresh.F90
  trunk/src/modules/par_mesh.F90
  trunk/src/mpi/par_aux.F90
  trunk/src/mpi/par_verify.F90
  trunk/src/solver/par_mumps/par_mumps_sc.F90
  trunk/src/solver/petsc/petsc_solve.F90
Labels: bug, ready-for-review

#99 Hotfix: refresh.F90
  trunk/src/meshmod/close_mesh.F90
  trunk/src/meshmod/refresh.F90
Labels: bug, minor

#100 Atomic counters when updating p and getting rid of some junk
  trunk/src/adapt/global_pref.F90
  trunk/src/meshmod/nodmod.F90
Labels: bug

#101 Removing accidentally pushed file
  trunk/problems/PRIMAL_DPG_HEEDONG/makefile
Labels: minor

#104 Switching indices to avoid temp arrays
  trunk/src/datstrs/neig_face.F90
Labels: enhancement, minor, ready-for-review

#108 Fixing a bug with DOF allocation for edges
  trunk/src/adapt/global_href.F90
  trunk/src/meshmod/close_mesh.F90
  trunk/src/meshmod/refresh.F90
  trunk/src/modules/par_mesh.F90
Labels: bug, ready-for-review

#102 Optimizing calls to `npar_ref`, `nson_ref`, `nort_ref`
  trunk/src/constrs/get_connect_info.F
  trunk/src/meshmod/util/elem_nodes_one.F90
  trunk/src/modules/refinements.F90
Labels: enhancement, ready-for-review

#103 Optimizing calls to `Type_nod`
  trunk/src/constrs/get_connect_info.F
  trunk/src/meshmod/util/elem_nodes_one.F90
  trunk/src/meshmod/util/find_element_closing_ref.F90
  trunk/src/meshmod/util/find_element_ref.F90
  trunk/src/modules/element_data.F
  trunk/src/modules/node_types.F90
  trunk/src/utility/print.F
Labels: enhancement, ready-for-review

#105 Improvement to PETSc solver interface
  trunk/problems/POISSON/GALERKIN/common/uniform_href.F90
  trunk/problems/POISSON/GALERKIN/exec_job.F90
  trunk/problems/POISSON/PRIMAL_DPG/common/uniform_href.F90
  trunk/problems/POISSON/PRIMAL_DPG/exec_case.F90
  trunk/problems/POISSON/PRIMAL_DPG/exec_job.F90
  trunk/src/solver/petsc/petsc_solve.F90
  trunk/src/solver/petsc/petsc_w_ksp.F90
Labels: enhancement, minor, ready-for-review

#106 h-adaptive tests for distributed hexa meshes
  trunk/files/control/control_0
  trunk/files/mesh/hexa27_orient_0
  trunk/files/mesh/hexa_orient_0
  trunk/files/physics/physics_0
  trunk/src/meshmod/close_mesh.F90
  trunk/src/meshmod/nodgen.F90
  trunk/src/modules/mpi_wrapper.F90
  trunk/src/modules/zoltan_wrapper.F90
  trunk/src/mpi/par_verify.F90
  trunk/test/hexa_adapt_h_aniso.F90
  trunk/test/hexa_adapt_h_iso.F90
  trunk/test/makefile
  trunk/test/random_refine.F90
Labels: ready-for-review, testing

#112 Test refine
  trunk/files/control/control_0
  trunk/files/mesh/hexa27_orient_0
  trunk/files/mesh/hexa_orient_0
  trunk/files/physics/physics_0
  trunk/src/meshmod/close_mesh.F90
  trunk/src/meshmod/nodgen.F90
  trunk/src/modules/mpi_wrapper.F90
  trunk/src/modules/zoltan_wrapper.F90
  trunk/src/mpi/par_verify.F90
  trunk/test/hexa_adapt_h_aniso.F90
  trunk/test/hexa_adapt_h_iso.F90
  trunk/test/makefile
  trunk/test/random_refine.F90
Labels: testing

#107 Unit tests for utilities
  trunk/makefile
  trunk/src/utility/cross_product.F90
  trunk/src/utility/decode.F90
  trunk/src/utility/decode2.F90
  trunk/src/utility/decodg.F90
  trunk/src/utility/encodg.F90
  trunk/src/utility/invert.F90
  trunk/src/utility/list.mk
  trunk/src/utility/near.F90
  trunk/test/cross_product.F90
  trunk/test/decode.F90
  trunk/test/dot_product.F90
  trunk/test/encod_decod.F90
  trunk/test/encode_decode_order.F90
  trunk/test/encodg_decodg.F90
  trunk/test/fact.F90
  trunk/test/hexa_adapt_h_case1.F90
  trunk/test/hexa_adapt_h_case1.txt
  trunk/test/invert.F90
  trunk/test/isgn.F90
  trunk/test/locate.F90
  trunk/test/locate_char.F90
  trunk/test/makefile
  trunk/test/near.F90
  trunk/test/real_imag.F90
  trunk/test/unused/jacobi.F
  trunk/test/unused/legendre.F
  trunk/test/unused/mie_coeff.F
  trunk/test/unused/time.F
Labels: ready-for-review, testing

#113 More Fortran style changes
  trunk/src/meshgen/hp3gen.F90
Labels: enhancement, minor

#88 Replacing `char(6) DTYPE(:)` with `integer D_TYPE(:)`
  trunk/problems/LASER/COMMON_FILES/norms.F90
  trunk/problems/LASER/UW_COUPLED/my_paraview_driver.F90
  trunk/problems/MAXWELL/GALERKIN/my_paraview_driver.F90
  trunk/problems/POISSON/GALERKIN/my_paraview_driver.F90
  trunk/problems/POISSON/PRIMAL_DPG/my_paraview_driver.F90
  trunk/problems/SHEATHED_HOSE/elem_residual.F90
  trunk/problems/SHEATHED_HOSE/exact_error.F90
  trunk/problems/SHEATHED_HOSE/my_paraview_driver.F90
  trunk/problems/SHEATHED_HOSE/paraview/soln2vtk.F90
  trunk/problems/SHEATHED_HOSE/refine_DPG.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/my_paraview_driver.F90
  trunk/src/constrs/celem_system.F90
  trunk/src/constrs/celem_systemI.F90
  trunk/src/datstrs/dof_in.F90
  trunk/src/datstrs/dof_out.F90
  trunk/src/datstrs/get_index.F90
  trunk/src/element/shape_1/CheckOrder.F
  trunk/src/element/shape_1/ContExactSequence.F
  trunk/src/element/shape_1/broken/BrokenExactSequence.F
  trunk/src/element/util/compute_error.F90
  trunk/src/graphics/paraview/paraview_driver.F90
  trunk/src/graphics/paraview/scalar2vtk.F90
  trunk/src/graphics/paraview/vector2vtk.F90
  trunk/src/graphics/x11/base/soldis_system.F90
  trunk/src/hpinterp/dhpvert.F90
  trunk/src/hpinterp/edge/dhpedgeE.F90
  trunk/src/hpinterp/edge/dhpedgeH.F90
  trunk/src/hpinterp/face/dhpfaceE.F90
  trunk/src/hpinterp/face/dhpfaceH.F90
  trunk/src/hpinterp/face/dhpfaceV.F90
  trunk/src/hpinterp/homogenD.F90
  trunk/src/hpinterp/update_Ddof.F90
  trunk/src/meshgen/read_input.F90
  trunk/src/modules/data_structure3D.F90
  trunk/src/modules/physics.F90
  trunk/src/modules/stc.F90
  trunk/src/modules/zoltan_wrapper.F90
  trunk/src/solver/frontal/interf/solout.F90
Labels: enhancement, ready-for-review

#71 Introducing Zoltan LB parameters
  trunk/problems/LASER/COMMON_FILES/norms.F90
  trunk/problems/LASER/COMMON_FILES/power.F90
  trunk/problems/LASER/COMMON_FILES/refine_DPG.F90
  trunk/problems/LASER/COMMON_FILES/residual.F90
  trunk/problems/LASER/COMMON_FILES/thermal.F90
  trunk/problems/LASER/UW_COUPLED/elem/elem.F90
  trunk/problems/LASER/UW_COUPLED/elem/elem_maxwell.F90
  trunk/problems/LASER/UW_COUPLED/elem/elem_maxwell_fi_hexa.F90
  trunk/problems/LASER/UW_COUPLED/elem/elem_maxwell_fi_pris.F90
  trunk/problems/LASER/UW_COUPLED/elem/elem_residual_maxwell.F90
  trunk/problems/LASER/UW_COUPLED/exec_job.F90
  trunk/problems/LASER/UW_COUPLED/exec_job_coupled.F90
  trunk/problems/LASER/UW_COUPLED/exec_job_heat.F90
  trunk/problems/LASER/UW_COUPLED/exec_job_nl.F90
  trunk/problems/LASER/UW_COUPLED/initialize.F90
  trunk/problems/LASER/UW_COUPLED/main.F90
  trunk/problems/MAXWELL/GALERKIN/common/initialize.F90
  trunk/problems/MAXWELL/GALERKIN/common/uniform_href.F90
  trunk/problems/MAXWELL/GALERKIN/exec_job.F90
  trunk/problems/MAXWELL/GALERKIN/main.F90
  trunk/problems/MPI_TEST/TEST/common/initialize.F90
  trunk/problems/POISSON/GALERKIN/common/initialize.F90
  trunk/problems/POISSON/GALERKIN/common/uniform_href.F90
  trunk/problems/POISSON/GALERKIN/exec_job.F90
  trunk/problems/POISSON/GALERKIN/main.F90
  trunk/problems/POISSON/PRIMAL_DPG/common/initialize.F90
  trunk/problems/POISSON/PRIMAL_DPG/common/residual.F90
  trunk/problems/POISSON/PRIMAL_DPG/common/uniform_href.F90
  trunk/problems/POISSON/PRIMAL_DPG/exec_job.F90
  trunk/problems/POISSON/PRIMAL_DPG/main.F90
  trunk/problems/SHEATHED_HOSE/common/initialize.F90
  trunk/problems/SHEATHED_HOSE/common/residual.F90
  trunk/problems/SHEATHED_HOSE/common/uniform_href.F90
  trunk/problems/SHEATHED_HOSE/exec_job.F90
  trunk/problems/SHEATHED_HOSE/main.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/common/initialize.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/common/uniform_href.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/exec_job.F90
  trunk/problems/VECTOR_POISSON/GALERKIN/main.F90
  trunk/src/adapt/enforce_min_rule.F90
  trunk/src/adapt/global_href.F90
  trunk/src/adapt/global_href_omp.F90
  trunk/src/graphics/paraview/geom2vtk.F90
  trunk/src/graphics/paraview/scalar2vtk.F90
  trunk/src/graphics/paraview/vector2vtk.F90
  trunk/src/hpinterp/update_Ddof.F90
  trunk/src/hpinterp/update_gdof.F90
  trunk/src/meshmod/close_mesh.F90
  trunk/src/modules/par_mesh.F90
  trunk/src/modules/zoltan_wrapper.F90
  trunk/src/solver/omp_mumps/mumps_sc.F90
  trunk/src/solver/par_mumps/par_fiber.F90
  trunk/src/solver/par_mumps/par_mumps_sc.F90
  trunk/src/solver/par_mumps/par_nested.F90
  trunk/src/solver/par_mumps/par_solve.F90
  trunk/src/solver/pardiso/pardiso_sc.F90
  trunk/src/solver/pardiso/pardiso_solve.F90
  trunk/src/solver/petsc/petsc_solve.F90
Labels: enhancement, minor, ready-for-review

#115 Minor fix make
  trunk/m_options_files/m_options_TACC_intel18
  trunk/m_options_files/m_options_TACC_intel19
  trunk/makefile
  trunk/src/modules/physics.F90
  trunk/src/solver/frontal/base/complex/makefile
  trunk/src/solver/frontal/base/real/makefile
Labels: minor, ready-for-review, make

#116 Bug fix in broken prism H(div) shape functions
  trunk/src/element/shape_1/broken/BrokenPrism.F
Labels: bug

#120 Citation file
  CITATION.cff
Labels: minor

#122 Adding convergence tests for H1 and H(curl) problems
  trunk/files/physics/physics_E
  trunk/files/physics/physics_H
  trunk/files/physics/physics_Q
  trunk/files/physics/physics_V
  trunk/src/solver/omp_mumps/mumps_sc.F90
  trunk/test/conv_maxw.F90
  trunk/test/conv_pois.F90
  trunk/test/makefile
  trunk/test/poly_maxw.F90
  trunk/test/poly_pois.F90
Labels: ready-for-review, testing

#123 Updates to test makefile
  trunk/test/conv_maxw.F90
  trunk/test/conv_pois.F90
  trunk/test/cross_product.F90
  trunk/test/decode.F90
  trunk/test/dot_product.F90
  trunk/test/encod_decod.F90
  trunk/test/encode_decode_order.F90
  trunk/test/encodg_decodg.F90
  trunk/test/fact.F90
  trunk/test/hexa_adapt_h_aniso.F90
  trunk/test/hexa_adapt_h_case1.F90
  trunk/test/hexa_adapt_h_iso.F90
  trunk/test/invert.F90
  trunk/test/isgn.F90
  trunk/test/locate.F90
  trunk/test/locate_char.F90
  trunk/test/makefile
  trunk/test/near.F90
  trunk/test/parameters.F90
  trunk/test/poly_maxw.F90
  trunk/test/poly_pois.F90
  trunk/test/real_imag.F90
Labels: ready-for-review, testing

#124 Removing GMP legacy files
  trunk/src/GMP/base/curve.F90
  trunk/src/GMP/base/curves/bezier.F90
  trunk/src/GMP/base/curves/list.mk
  trunk/src/GMP/base/fig_trian.F90
  trunk/src/GMP/base/input_DEFAULT.F90
  trunk/src/GMP/base/input_NETGEN.F
  trunk/src/GMP/base/input_RECONSTRUCT.F
  trunk/src/GMP/base/list.mk
  trunk/src/GMP/base/read_geometry.F90
  trunk/src/GMP/base/reconstruct/TODO
  trunk/src/GMP/base/reconstruct/base/check_edge.F
  trunk/src/GMP/base/reconstruct/base/list.mk
  trunk/src/GMP/base/reconstruct/base/reconstruct_curve.F
  trunk/src/GMP/base/reconstruct/base/reconstruct_normal.F
  trunk/src/GMP/base/reconstruct/base/reconstruct_sharp_edge_curve.F
  trunk/src/GMP/base/reconstruct/base/set_sharp_edge_bundle.F
  trunk/src/GMP/base/reconstruct/quads/reconstructQ.F
  trunk/src/GMP/base/reconstruct/quads/reconstruct_Qpatch.F
  trunk/src/GMP/base/reconstruct/quads/reconstruct_curvatureQ.F
  trunk/src/GMP/base/reconstruct/quads/set_bundleQ.F
  trunk/src/GMP/base/reconstruct/quads/set_tangentsQ.F
  trunk/src/GMP/base/reconstruct/trian/list.mk
  trunk/src/GMP/base/reconstruct/trian/reconstructT.F
  trunk/src/GMP/base/reconstruct/trian/reconstruct_Tpatch.F
  trunk/src/GMP/base/reconstruct/trian/reconstruct_curvatureT.F
  trunk/src/GMP/base/reconstruct/trian/set_bundleT.F
  trunk/src/GMP/base/reconstruct/trian/set_tangentsT.F
  trunk/src/GMP/base/reconstruct/util/check_derivative.F90
  trunk/src/GMP/base/reconstruct/util/check_tri2edgs_compatibility.F90
  trunk/src/GMP/base/reconstruct/util/collect_tangent.F
  trunk/src/GMP/base/reconstruct/util/compute_coefficients.F90
  trunk/src/GMP/base/reconstruct/util/compute_radial_derivative.F90
  trunk/src/GMP/base/reconstruct/util/generate_Bezier_curve.F90
  trunk/src/GMP/base/reconstruct/util/generate_Bezier_triangle.F90
  trunk/src/GMP/base/reconstruct/util/list.mk
  trunk/src/GMP/base/reconstruct/util/radial_derivative.F90
  trunk/src/GMP/base/triangles/list.mk
  trunk/src/GMP/base/triangles/trian_G1RecTri.F90
  trunk/src/GMP/base/upgrade2double.F90
  trunk/src/GMP/module/GMP.F
  trunk/src/GMP/module/PML.F90
  trunk/src/GMP/module/U2D.F90
  trunk/src/GMP/module/list.mk
  trunk/src/GMP/shape_0/Hkernels.F
  trunk/src/GMP/shape_0/Hshape1.F
  trunk/src/GMP/shape_0/list.mk
  trunk/src/GMP/util/add_void_curve.F90
  trunk/src/GMP/util/bernstein_poly.F90
  trunk/src/GMP/util/biv_bernstein_poly.F90
  trunk/src/GMP/util/find_GMPtriangle.F90
  trunk/src/GMP/util/list.mk
Labels: legacy
