Repository Oden-EAG/hp3d, pull requests merged in 2023-07, with the labels that each got.

#110 New features, bug fixes, and performance optimizations
  trunk/files/vis/hexa27
  trunk/files/vis/prism18
  trunk/files/vis/tetra10
  trunk/makefile
  trunk/src/adapt/enforce_min_rule.F90
  trunk/src/constrs/flag_constr_parents.F
  trunk/src/constrs/flag_constr_parents.F90
  trunk/src/constrs/list.mk
  trunk/src/graphics/paraview/geom2vtk.F90
  trunk/src/graphics/paraview/paraview_geom.F90
  trunk/src/graphics/paraview/scalar2vtk.F90
  trunk/src/graphics/paraview/vector2vtk.F90
  trunk/src/hpinterp/update_Ddof.F90
  trunk/src/hpinterp/update_gdof.F90
  trunk/src/meshmod/close_mesh.F90
  trunk/src/meshmod/refresh.F90
  trunk/src/meshmod/util/elem_show.F90
  trunk/src/modules/bitvisit.F90
  trunk/src/modules/data_structure3D.F90
  trunk/src/modules/element_data.F
  trunk/src/modules/index_map.F90
  trunk/src/modules/list.mk
  trunk/src/modules/mpi_wrapper.F90
  trunk/src/modules/par_ghost.F90
  trunk/src/modules/par_mesh.F90
  trunk/src/modules/paraview.F90
  trunk/src/modules/refinements.F90
  trunk/src/modules/sorts.F90
  trunk/src/modules/stc.F90
  trunk/src/modules/upscale.F90
  trunk/src/modules/zoltan_wrapper.F90
  trunk/src/mpi/par_aux.F90
  trunk/src/mpi/zoltan_lb_param.F90
Labels: enhancement

#127 Ultraweak DPG Poisson Model Problem
  trunk/makefile
  trunk/problems/POISSON/ULTRAWEAK_DPG/celem.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/dirichlet.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/exact.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/exact_error.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/ficheracornerdirichlet.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/finalize.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/getf.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/initialize.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/refine_DPG.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/residual.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/set_environment.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/solution.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/uniform_href.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/control/control
  trunk/problems/POISSON/ULTRAWEAK_DPG/elem.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/elem_residual.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/exec_case.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/exec_job.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/exec_job_adap_ref.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/geometries/fichera_corner
  trunk/problems/POISSON/ULTRAWEAK_DPG/geometries/hexa_orient0
  trunk/problems/POISSON/ULTRAWEAK_DPG/input/physics
  trunk/problems/POISSON/ULTRAWEAK_DPG/main.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/make.inc
  trunk/problems/POISSON/ULTRAWEAK_DPG/makefile
  trunk/problems/POISSON/ULTRAWEAK_DPG/modules/common_prob_data.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/my_paraview_driver.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/run.sh
  trunk/problems/POISSON/ULTRAWEAK_DPG/set_initial_mesh.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/soldis.F90
Labels: ready-for-review, application

#130 Formatting and clean-up UW DPG Poisson problem
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/dirichlet.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/exact_error.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/ficheracornerdirichlet.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/residual.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/control/control
  trunk/problems/POISSON/ULTRAWEAK_DPG/elem.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/input/physics
  trunk/problems/POISSON/ULTRAWEAK_DPG/main.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/set_initial_mesh.F90
Labels: minor, application
