Repository Oden-EAG/hp3d, pull requests merged in 2023-09, with the labels that each got.

#133 Ultraweak Maxwell problem
  trunk/makefile
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/celem.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/common/commonRoutines.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/common/exact_error.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/common/mfd_solutions.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/common/residual.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/common/set_environment.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/control/control
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/dirichlet.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/elem/elem.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/elem/elem_maxwell.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/elem/elem_residual.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/elem/elem_residual_maxwell.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/exact.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/exec_case.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/exec_job.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/finalize.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/geometries/cube
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/geometries/prism
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/geometries/tet
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/getf.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/initialize.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/input/physics
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/main.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/make.inc
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/makefile
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/modules/commonParam.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/my_paraview_driver.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/refine_DPG.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/run.sh
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/set_initial_mesh.F90
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/soldis.F90
Labels: application

#145 ParaView: write `pvd` files for `VTU` time series
  .gitignore
  AUTHORS
  trunk/problems/MAXWELL/GALERKIN/makefile
  trunk/problems/MAXWELL/ULTRAWEAK_DPG/makefile
  trunk/problems/POISSON/GALERKIN/makefile
  trunk/problems/POISSON/PRIMAL_DPG/makefile
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/exact_error.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/common/ficheracornerdirichlet.F90
  trunk/problems/POISSON/ULTRAWEAK_DPG/makefile
  trunk/problems/POISSON/ULTRAWEAK_DPG/run.sh
  trunk/problems/SHEATHED_HOSE/makefile
  trunk/problems/VECTOR_POISSON/GALERKIN/makefile
  trunk/src/graphics/paraview/geom2vtk.F90
  trunk/src/graphics/paraview/paraview_driver.F90
  trunk/src/graphics/paraview/paraview_initialize.F90
  trunk/src/graphics/paraview/vtu.F90
  trunk/src/modules/parameters.F90
  trunk/src/modules/paraview.F90
Labels: enhancement, ready-for-review

#144 New functions for `nvert`, `nedge`, `nface`
  trunk/src/datstrs/find_order.F90
  trunk/src/datstrs/find_orient.F90
  trunk/src/hpinterp/dhpvert.F90
  trunk/src/modules/node_types.F90
  trunk/test/conv_pois.F90
  trunk/test/poly_pois.F90
Labels: minor, ready-for-review

#149 Fixing an issue with `hp3d_dumpout` and `hp3d_dumpin` routines
  trunk/src/meshmod/close_mesh.F90
  trunk/src/modules/data_structure3D.F90
  trunk/src/modules/par_mesh.F90
  trunk/test/attr_to_index.F90
  trunk/test/index_to_attr.F90
Labels: bug

#151 minor fix in `LASER` app
  trunk/problems/LASER/UW_COUPLED/exec_job_coupled.F90
  trunk/problems/LASER/UW_COUPLED/exec_job_nl.F90
Labels: minor
